export interface FontFamily {
  name: string
  category: 'sans-serif' | 'serif' | 'display' | 'script' | 'monospace'
}

export const FONT_FAMILIES: FontFamily[] = [
  // Sans-serif
  { name: 'Arial',            category: 'sans-serif' },
  { name: 'Helvetica',        category: 'sans-serif' },
  { name: 'Verdana',          category: 'sans-serif' },
  { name: 'Tahoma',           category: 'sans-serif' },
  { name: 'Trebuchet MS',     category: 'sans-serif' },
  { name: 'Impact',           category: 'sans-serif' },
  { name: 'Roboto',           category: 'sans-serif' },
  { name: 'Open Sans',        category: 'sans-serif' },
  { name: 'Lato',             category: 'sans-serif' },
  { name: 'Montserrat',       category: 'sans-serif' },
  { name: 'Oswald',           category: 'sans-serif' },
  { name: 'Raleway',          category: 'sans-serif' },
  { name: 'PT Sans',          category: 'sans-serif' },
  { name: 'Ubuntu',           category: 'sans-serif' },
  { name: 'Nunito',           category: 'sans-serif' },
  { name: 'Poppins',          category: 'sans-serif' },
  { name: 'Inter',            category: 'sans-serif' },
  { name: 'Barlow',           category: 'sans-serif' },
  { name: 'Mulish',           category: 'sans-serif' },
  { name: 'Outfit',           category: 'sans-serif' },
  { name: 'DM Sans',          category: 'sans-serif' },
  { name: 'Exo 2',            category: 'sans-serif' },
  { name: 'Cabin',            category: 'sans-serif' },
  { name: 'Karla',            category: 'sans-serif' },
  { name: 'Josefin Sans',     category: 'sans-serif' },
  // Serif
  { name: 'Times New Roman',       category: 'serif' },
  { name: 'Georgia',               category: 'serif' },
  { name: 'Garamond',              category: 'serif' },
  { name: 'Merriweather',          category: 'serif' },
  { name: 'Playfair Display',      category: 'serif' },
  { name: 'Libre Baskerville',     category: 'serif' },
  { name: 'Lora',                  category: 'serif' },
  { name: 'Crimson Text',          category: 'serif' },
  { name: 'EB Garamond',           category: 'serif' },
  { name: 'Cormorant Garamond',    category: 'serif' },
  { name: 'PT Serif',              category: 'serif' },
  { name: 'Bitter',                category: 'serif' },
  { name: 'Domine',                category: 'serif' },
  { name: 'Spectral',              category: 'serif' },
  { name: 'Zilla Slab',            category: 'serif' },
  // Display / Decorative
  { name: 'Bebas Neue',      category: 'display' },
  { name: 'Anton',           category: 'display' },
  { name: 'Abril Fatface',   category: 'display' },
  { name: 'Bangers',         category: 'display' },
  { name: 'Boogaloo',        category: 'display' },
  { name: 'Chewy',           category: 'display' },
  { name: 'Lilita One',      category: 'display' },
  { name: 'Righteous',       category: 'display' },
  { name: 'Russo One',       category: 'display' },
  { name: 'Squada One',      category: 'display' },
  { name: 'Ultra',           category: 'display' },
  { name: 'Titan One',       category: 'display' },
  { name: 'Black Han Sans',  category: 'display' },
  { name: 'Alfa Slab One',   category: 'display' },
  { name: 'Bree Serif',      category: 'display' },
  // Script / Handwriting
  { name: 'Dancing Script',   category: 'script' },
  { name: 'Pacifico',         category: 'script' },
  { name: 'Lobster',          category: 'script' },
  { name: 'Great Vibes',      category: 'script' },
  { name: 'Satisfy',          category: 'script' },
  { name: 'Caveat',           category: 'script' },
  { name: 'Permanent Marker', category: 'script' },
  { name: 'Cookie',           category: 'script' },
  { name: 'Kaushan Script',   category: 'script' },
  { name: 'Sacramento',       category: 'script' },
  { name: 'Allura',           category: 'script' },
  { name: 'Alex Brush',       category: 'script' },
  { name: 'Marck Script',     category: 'script' },
  { name: 'Amatic SC',        category: 'script' },
  { name: 'Indie Flower',     category: 'script' },
  // Monospace
  { name: 'Courier New',      category: 'monospace' },
  { name: 'DM Mono',          category: 'monospace' },
  { name: 'Source Code Pro',  category: 'monospace' },
  { name: 'Space Mono',       category: 'monospace' },
  { name: 'Roboto Mono',      category: 'monospace' },
  { name: 'JetBrains Mono',   category: 'monospace' },
  { name: 'IBM Plex Mono',    category: 'monospace' },
  { name: 'Fira Code',        category: 'monospace' },
  { name: 'Inconsolata',      category: 'monospace' },
]

export const CATEGORY_LABELS: Record<FontFamily['category'], string> = {
  'sans-serif': 'Sans-serif',
  'serif':      'Serif',
  'display':    'Display',
  'script':     'Script',
  'monospace':  'Monospace',
}

export const TEXT_STYLES: string[] = [
  'Bold',
  'Italic',
  'Underline',
  'Strikethrough',
  'Outline',
  'Shadow',
  'Glow',
  'Emboss',
  'Color fill',
  'Gradient fill',
  'Letter spacing',
  'Line height',
  'All caps',
  'Opacity',
]
